<!DOCTYPE HTML>
<html lang="en-US">
   <head>
      <meta charset="UTF-8">
      <title>Privacy Policy | PITCHAR.IO</title>
 <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="css/bootstrap.min.css">
      <link rel="stylesheet" href="css/style.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
      <?php include 'favicon.php'; ?>
   </head>
   <body>
<h1 style="line-height: 1.65789; margin: 0pt -11pt; text-align: left; padding-left: 60px;"><strong><span style="font-size: 19pt; font-family: Arial; color: #000000; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">PITCHAR.IO</span></strong></h1>
<!-- <p style="line-height: 1.38; margin: 0pt -11pt 8pt; text-align: left; padding-left: 60px;"><strong><span style="font-size: 12pt; font-family: Arial; color: #000000; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Privacy Policy of https://pitchar.io/</span></strong></p> -->
<pre>
<h1 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 22.5pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Privacy Policy</span></h1>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Effective date: September 20, 2018</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">PITCHAR.IO ("us", "we", or "our") operates the https://pitchar.io website (the "Service").</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. </span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://pitchar.io</span></p>
<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Information Collection And Use</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We collect several different types of information for various purposes to provide and improve our Service to you.</span></p>
<h3 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 15pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Types of Data Collected</span></h3>
<h4 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Personal Data</span></h4>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Email address</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Phone number</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Address, State, Province, ZIP/Postal code, City</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Cookies and Usage Data</span></p>
<h4 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Usage Data</span></h4>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</span></p>
<h4 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Tracking &amp; Cookies Data</span></h4>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Examples of Cookies we use:</span></p>
<p style="padding-left: 60px;"><strong><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Session Cookies.</span></strong><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> We use Session Cookies to operate our Service.</span></p>
<p style="padding-left: 60px;"><strong><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Preference Cookies.</span></strong><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> We use Preference Cookies to remember your preferences and various settings.</span></p>
<p style="padding-left: 60px;"><strong><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Security Cookies.</span></strong><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> We use Security Cookies for security purposes.</span></p>
<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Use of Data</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">PITCHAR.IO uses the collected data for various purposes:</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To provide and maintain the Service</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To notify you about changes to our Service</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To allow you to participate in interactive features of our Service when you choose to do so</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To provide customer care and support</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To provide analysis or valuable information so that we can improve the Service</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To monitor the usage of the Service</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To detect, prevent and address technical issues</span></p>
<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Transfer Of Data</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Your information, including Personal Data, may be transferred to &mdash; and maintained on &mdash; computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">PITCHAR.IO Publications Pvt. Ltd. will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</span></p>
<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Disclosure Of Data</span></h2>
<h3 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 15pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Legal Requirements</span></h3>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">PITCHAR.IO Publications Pvt. Ltd. may disclose your Personal Data in the good faith belief that such action is necessary to:</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To comply with a legal obligation</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To protect and defend the rights or property of PITCHAR.IO </span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To prevent or investigate possible wrongdoing in connection with the Service</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To protect the personal safety of users of the Service or the public</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To protect against legal liability</span></p>
<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Security Of Data</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</span></p>
<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Service Providers</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</span></p>
<h3 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 15pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Analytics</span></h3>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We may use third-party Service Providers to monitor and analyze the use of our Service.</span></p>
<p style="padding-left: 60px;"><strong><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Google Analytics</span></strong></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: </span><a style="text-decoration: none;" href="https://policies.google.com/privacy?hl=en"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">https://policies.google.com/privacy?hl=en</span></a></p>
<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Links To Other Sites</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</span></p>
<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Children's Privacy</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Our Service does not address anyone under the age of 18 ("Children").</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</span></p>
<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Changes To This Privacy Policy</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</span></p>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</span></p>
<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Contact Us</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">If you have any questions about this Privacy Policy, please contact us:</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">By email: info@pitchar.io</span></p>
<p style="text-align: left; padding-left: 60px;">&nbsp;</p>
</pre>
   </body>
</html>
<!--Design And develope By Yash Gupta - Hello@yashgupta.work -->



