<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Terms of Use | PITCHAR.IO</title>
 <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="css/bootstrap.min.css">
      <link rel="stylesheet" href="css/style.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
      <?php include 'favicon.php'; ?>
</head>
<body>
<h1 style="line-height: 1.65789; margin: 0pt -11pt; text-align: left; padding-left: 60px;"><strong><span style="font-size: 19pt; font-family: Arial; color: #000000; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">PITCHAR.IO</span></strong></h1>
<pre>
<h1 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 22.5pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">TERMS OF USE:</span></h1>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Terms Of Use(“Agreement”) govern your use of PITCHAR.IO website, email newsletters referred as Services and any “Content” listed on our website. This agreement is between the providers (“we”, “us”, “our”) and you. By utilizing our Services, you are confirming that you have perused and comprehended this Agreement (including our Privacy Policy), consenting to turn into a gathering to this Agreement and consenting to be bound by and consent to the terms and conditions thus. In the event that, for any reason, you don’t acknowledge and consent to all the terms and states of this Agreement, kindly don’t get to or utilize the Services as a part of any way.

<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">For purposes of this Agreement, the term “Content” includes data, information, text, logos, photos, videos, audio clips, written posts, software, graphics, programming, themes through the Services, including the User Content as defined below.

<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">ELIGIBILITY</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Services provided by PITCHAR.IO website are intended only for users above 18 years old. By getting to and utilizing the Services, you guarantee to us that you are atleast 18 years of age. In the event that you are not yet 18 years of age, please stop using the services provided by our website.

<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">USER CONTENT</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Some portion of website may allow users to create the content. You hold your rights in such User Content, and by submitting or posting User Content, you are giving us an irreversible, completely paid, royalty-free license to utilize, showcase, duplicate, imitate, alter, the content of your post. You agree to not use the Service to submit or link to any Content which is defamatory, abusive, hateful, threatening, spam or spam-like, likely to offend, contains adult or objectionable content, contains personal information of others, risks copyright infringement, encourages unlawful activity, or otherwise violates any laws. All Content you submit or upload may be reviewed by staff members. All Content you submit or upload may be sent to third-party verification services (including, but not limited to, spam prevention services). Do not submit any Content that you consider to be private or confidential.</span></p>

<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">LOGIN AND SIGNUP</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Certain features of website required you to login using third party services such as Facebook for commenting under posts. By logging-in through the third party for commenting on posts, you permit us to access limited information from your profile such as your Name, Email Address etc in accordance with our Privacy Policy.</span></p>

<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">INTELLECTUAL PROPERTY RIGHTS</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">All rights including the Content and Services will have exclusive rights of PITCHAR.IO website. You should not copy,transmit, reproduce, reverse engineer, decrypt, distribute or disassemble the Content or Services offered by us without our written consent. You likewise recognize and concur that any input, remarks or proposals you may give in regards to the Services is altogether intentional and we will be allowed to utilize such criticism, remarks or recommendations as we see fit and without any commitment or remuneration to you.</span></p>

<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">REPORTING INTELLECTUAL PROPERTY INFRINGEMENT</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We try hard that content posted on our website is original and is not copyright. If you feel that your copyright work has been copied and posted in such a way that it leads to copyright infringement then please let us know the following information:- a) Original content information b) Your name, email address, postal address, & mobile number c) A statement that information provided by you is correct to your knowledge and if you are not the original copyright owner then you are authorized to act on his behalf Send us the requested information at mail@PITCHAR.IO We will take the appropriate action as per Copyright law and we will remove the content from our website.</span></p>

<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">DISCLAIMER REGARDING THIRD PARTY LINKS</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Content in our website may contain the link to third party websites. These third party websites might contain information that is inappropriate and offensive which is beyond our control. We should not be held responsible for any kind of misleading content on third party websites. Publicparrot does not guarantee, approve or endorse the information or products available at third party sites, nor does a link indicate any association with or endorsement by the linked site to PITCHAR.IO</span></p>

<h2 style="line-height: 1.32; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CHANGES TO THIS AGREEMENT</span></h2>
<p style="line-height: 1.65; margin: 0pt -11pt 23pt; text-align: left; padding-left: 60px;"><span style="font-size: 12pt; font-family: Arial; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We claim all authority to amend this Agreement at our sole discretion without former notice and whenever. The most recent Agreement will be posted here. By keeping on using the Services after changes are made, you consent to be bound by the revised Agreement.</span></p>

</pre>
</body>
</html>